# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Giwlxr91e3IQMQXX4tbpA8bU59KpKRvW
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# -----------------------------
# Load Models & Preprocessing Pipeline
# -----------------------------
@st.cache_resource
def load_models():
    classifier = joblib.load("best_classifier.pkl")
    regressor = joblib.load("best_regressor.pkl")
    pipeline = joblib.load("preprocess_pipeline.pkl")
    return classifier, regressor, pipeline

classifier, regressor, preprocess_pipeline = load_models()

# -----------------------------
# Streamlit UI
# -----------------------------
st.set_page_config(page_title="Real Estate Investment Advisor", layout="wide")

st.title("🏠 Real Estate Investment Advisor")
st.write("Predict whether a property is a **Good Investment** and its **Estimated Price After 5 Years**.")

# -----------------------------
# User Input Form
# -----------------------------
st.header("📄 Enter Property Details")

# Example Input Fields – update based on your dataset features
state = st.selectbox("State", ["Telangana", "Karnataka", "Maharashtra", "Tamil Nadu", "Delhi"])
city = st.text_input("City")
locality = st.text_input("Locality")
property_type = st.selectbox("Property Type", ["Apartment", "Villa", "Independent House"])
bhk = st.number_input("BHK", min_value=1, max_value=10, value=2)
size_sqft = st.number_input("Size in SqFt", min_value=300, max_value=10000, value=1000)
price_in_lakhs = st.number_input("Current Price (in Lakhs)", min_value=1.0, value=50.0)
age_property = st.number_input("Age of Property (Years)", min_value=0, max_value=50, value=5)
nearby_schools = st.number_input("Nearby Schools", min_value=0, max_value=20, value=3)
nearby_hospitals = st.number_input("Nearby Hospitals", min_value=0, max_value=20, value=2)

# Prepare input as DataFrame (must match training format)
input_data = pd.DataFrame([{
    "State": state,
    "City": city,
    "Locality": locality,
    "Property_Type": property_type,
    "BHK": bhk,
    "Size_in_SqFt": size_sqft,
    "Price_in_Lakhs": price_in_lakhs,
    "Age_of_Property": age_property,
    "Nearby_Schools": nearby_schools,
    "Nearby_Hospitals": nearby_hospitals
}])

# -----------------------------
# Prediction Button
# -----------------------------
if st.button("Predict Investment Outcome"):

    # Apply preprocessing
    processed_input = preprocess_pipeline.transform(input_data)

    # -----------------------------
    # Classification Prediction
    # -----------------------------
    is_good = classifier.predict(processed_input)[0]
    prob_good = classifier.predict_proba(processed_input)[0][1]

    # -----------------------------
    # Regression Prediction
    # -----------------------------
    future_price = regressor.predict(processed_input)[0]

    # -----------------------------
    # Display Results
    # -----------------------------
    st.subheader("📊 Prediction Results")

    if is_good == 1:
        st.success(f"✔ The property **IS a Good Investment** ({prob_good*100:.2f}% confidence)")
    else:
        st.error(f"✖ This property **may NOT be a good investment** ({prob_good*100:.2f}% confidence)")

    st.info(f"💰 **Estimated Price After 5 Years:** ₹ {future_price:.2f} Lakhs")


# Footer
st.caption("© 2024 Real Estate Investment Advisor | Powered by Streamlit + MLflow + Render")